GET http://localhost:8080/

###
GET http://localhost:8080/welcome-text

###
GET http://localhost:8080/orders

###
GET http://localhost:8080/orders/1

###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "size": "large",
  "type":  "Z pieczarkami",
  "comment": "No"
}

###
DELETE http://localhost:8080/orders/1

###
GET http://localhost:8080/admin/users

###
POST http://localhost:8080/admin/users
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "test",
  "age": 25
}

###
POST http://localhost:8080/login?username=user&password=72600bd5-3a66-4501-b529-8dbb32dfbd58

###
POST http://localhost:8080/logout

